### PR TITLE
Setup front-end tools and plugins we need to get started.

### PR DESCRIPTION
**Pull request by ayushbhagat**
Corresponds to https://github.com/uwblueprint/somo/issues/1.

### CODE REVIEW

**Review by sitefeng — APPROVED** [review]
ship it

**Comment by ayushbhagat** [comment]
@sitefeng Still need to setup a basic Redux action/reducer. I'll do that first and then merge it with master.

**Comment by chrisjluc** [comment]
Nice! So excited to finally start this 👍

**Comment by chrisjluc** [comment]
LGTM, how do we change the project so it passes on circleci? (We can do this in a separate PR.)

**Pull request merged**
