### PR TITLE
Modify extraneous dependency workaround to enable code coverage

### PR DESCRIPTION
**Pull request by hkjayakumar**
The `error` string has been changed to `2`

### CODE REVIEW

**Comment by hkjayakumar** [comment]
Self-reviewed

**Comment by ayushbhagat** [comment]
`2` is the same as `error` (see http://eslint.org/docs/user-guide/configuring#configuring-rules), so it wouldn't have solved the code coverage problem I would assume. :p

**Comment by hkjayakumar** [comment]
No, it did solve it because code climate was using an earlier version of eslint and checking for a numeric value or something in that line

**Comment by ayushbhagat** [comment]
Oh I see. So does it work now? Do we get the code coverage?

**Comment by hkjayakumar** [comment]
No, still need to fix something, I'll look into it soon

https://github.com/uwblueprint/somo/issues/65

**Pull request merged**
